### YamlMime:Sample
sample:
- name: Bindview Network Configuration Utility
  description: An application that demonstrates how to use INetCfg APIs to enumerate, install, uninstall, bind and unbind network components.
  generateZip: true
  preserveParentHierarchy: true
  author: windows-driver-samples
  languages:
  - cpp
  technologies:
  - windows
  vssolution: /network/config/bindview/bindview.sln
