name: Build all driver samples
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Retrieve and build all available solutions
        run: |
          .\Build-AllSamples.ps1 -Verbose
        env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}

      - name: Archive logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: _logs
